# Generated by Django 4.1.3 on 2022-11-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0003_rename_orderdetails_orderdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='brgy',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='full_address',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='brgy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='full_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
