# Generated by Django 4.1.3 on 2022-12-07 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0011_customer_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='is_admin',
            new_name='is_superuser',
        ),
    ]
