# Generated by Django 4.1.4 on 2022-12-09 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webpage', '0012_rename_is_admin_customer_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddedToCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('is_pending', models.BooleanField(default=True)),
                ('is_selected', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('estimated_time', models.IntegerField()),
                ('date_ordered', models.DateTimeField()),
                ('order_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('product_id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('product_name', models.CharField(blank=True, max_length=50, null=True)),
                ('product_price', models.IntegerField()),
                ('stocks', models.IntegerField()),
                ('stall_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='Customer',
        ),
        migrations.DeleteModel(
            name='product',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='is_superuser',
        ),
        migrations.AddField(
            model_name='customer',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='stall_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='OrderDetail',
        ),
        migrations.AddField(
            model_name='orders',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.customer'),
        ),
        migrations.AddField(
            model_name='addedtocart',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.customer'),
        ),
        migrations.AddField(
            model_name='addedtocart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.productlist'),
        ),
    ]
