# Generated by Django 4.1.4 on 2022-12-10 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0016_orders_shop_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='addedtocart',
            name='cart_id',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
    ]
