# Generated by Django 4.1.4 on 2022-12-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0017_addedtocart_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addedtocart',
            name='id',
        ),
        migrations.AlterField(
            model_name='addedtocart',
            name='cart_id',
            field=models.CharField(default=None, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
