# Generated by Django 4.1.5 on 2023-01-12 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0020_imagemodel_delete_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageModel',
        ),
    ]
