# Generated by Django 4.1.5 on 2023-01-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0022_addedtocart_total_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total_items',
            field=models.IntegerField(default=0),
        ),
    ]
