# Generated by Django 4.1.5 on 2023-01-17 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0023_orders_total_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='total_items',
            new_name='total_orders',
        ),
    ]
