# Generated by Django 4.1.5 on 2023-01-17 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0024_rename_total_items_orders_total_orders'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addedtocart',
            old_name='total_items',
            new_name='total_of_items',
        ),
    ]
