# Generated by Django 4.1.5 on 2023-01-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0025_rename_total_items_addedtocart_total_of_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
